id: I4AC4E4CA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:55:49+00:00'
last_modified: '2022-06-07T18:40:03.256358+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017863
  title: སྔོ་འབུམ་སྨན་གྱི་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88F8:
      image_group_id: I1PD456
      title: ''
      total_pages: 440
      order: 1
      base_file: 88F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
