id: P003253
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:50:31.881838
source_metadata:
  id: bdr:W00EGS1017863
  title: སྔོ་འབུམ་སྨན་གྱི་གཏེར་མཛོད
  author: ''
  volumes:
    374dda404d964d26a11672e991ba5e3f:
      image_group_id: I1PD456
      title: ''
      volume_number: 1
      total_pages: 440
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
