id: P003253
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017863
  title: སྔོ་འབུམ་སྨན་གྱི་གཏེར་མཛོད
  author: ''
  volumes:
    374dda404d964d26a11672e991ba5e3f:
      image_group_id: I1PD456
      title: ''
      volume_number: 1
      total_pages: 440
      base_file: v001.txt
